# Generated by Django 3.2.9 on 2021-12-02 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainStorage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savefile',
            name='time_save',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки'),
        ),
        migrations.AlterField(
            model_name='savefile',
            name='time_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата редактирования'),
        ),
        migrations.AlterField(
            model_name='savefile',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Наименование'),
        ),
    ]
