# Generated by Django 3.2.9 on 2021-12-02 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainStorage', '0002_auto_20211202_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savefile',
            name='file_describe',
            field=models.CharField(max_length=255, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='savefile',
            name='saveFile',
            field=models.FileField(upload_to='uploads/%Y/%m/%d/', verbose_name='Файл'),
        ),
    ]
